In [147]:
import pandas as pd
import numpy as np
import re
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')

In [148]:
df = pd.read_csv('properatti_clean.csv')
df.head(2)

,Unnamed: 0,barrio,lat,lon,total,cubierta,precio,piso,habs,expensas,descripcion
0,2,Mataderos,-34.652262,-58.522982,55.0,55.0,1309.090909,NaN,NaN,NaN,2 AMBIENTES 3ER PISO LATERAL LIVING COMEDOR AM...
1,7,Belgrano,-34.559873,-58.443362,45.0,40.0,3066.666667,NaN,NaN,NaN,EXCELENTE MONOAMBIENTE A ESTRENAR AMPLIO SUPER...

In [149]:
#Cantidad de Observaciones por Variable
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15948 entries, 0 to 15947
Data columns (total 11 columns):
Unnamed: 0     15948 non-null int64
barrio         15948 non-null object
lat            15948 non-null float64
lon            15948 non-null float64
total          15948 non-null float64
cubierta       15491 non-null float64
precio         15948 non-null float64
piso           2465 non-null float64
habs           10109 non-null float64
expensas       3956 non-null float64
descripcion    15948 non-null object
dtypes: float64(8), int64(1), object(2)
memory usage: 1.3+ MB

Diccionario para mapear los textos a numeros

In [150]:
numeros_en_letras = {'uno' : '1' , 'dos' : '2' , 'tres' : '3' , 'cuatro' : '4' , 'cinco' : '5' , 'seis' : '6' , 'siete' : '7' , 'mono' : '1' , 'mon' : '1' , 'nan' : np.nan}

Aca seteamos la REGEX para extraer la cantidad de ambientes

In [151]:
pattern = r'(uno\s|dos\s|tres\s|cuatro\s|cinco\s|seis\s|siete\s|\d+?\s|mono?)amb{0,1}'
df['ambientes'] = ""
df['ambientes'] = df['descripcion'].str.extract(pattern , flags=re.IGNORECASE , expand=True)

In [152]:
check = df
print("Cantidad de Observaciones nuevas --> " , check[(check['habs'].isnull()) & (check['ambientes'].notnull())].count()['ambientes'])

Cantidad de Observaciones nuevas -->  4386

In [153]:
df['ambientes'] = df['ambientes'].str.lower()
df['ambientes'].unique()

array(['2 ', 'mono', 'dos ', nan, 'cuatro ', '3 ', '4 ', '1 ', '5 ', '6 ',
       'tres ', '042 ', 'dos\xa0', '42026 ', 'cuatro\xa0', '902 ', '18 ',
       '000 ', 'cinco ', '944 ', 'tres\xa0', '7 ', '8 ', '12 ', '43 ',
       '22 ', '42022 ', '281 ', '24 ', '20173 ', '1200 ', '772 ', '653 ',
       '983 ', '42025 ', '42004 ', '42046 ', '502 ', '42049 ', '152 ',
       '412 ', '42015 ', '42021 ', '172 ', 'mon', '693 ', '622 ', '183 ',
       '793 ', '262 ', '253 ', '913 ', '20171 ', '20172 ', '853 ', '202 ',
       '192 ', '113 ', '2004 ', '822 ', '562 ', '23 ', '164 ', '733 ',
       '312 '], dtype=object)

In [154]:
df['ambientes'] = df['ambientes'].astype('str')
df['ambientes'].dtypes

dtype('O')

In [155]:
df['ambientes'] = df['ambientes'].str.strip()
df['ambientes'].unique()

array(['2', 'mono', 'dos', 'nan', 'cuatro', '3', '4', '1', '5', '6',
       'tres', '042', '42026', '902', '18', '000', 'cinco', '944', '7',
       '8', '12', '43', '22', '42022', '281', '24', '20173', '1200',
       '772', '653', '983', '42025', '42004', '42046', '502', '42049',
       '152', '412', '42015', '42021', '172', 'mon', '693', '622', '183',
       '793', '262', '253', '913', '20171', '20172', '853', '202', '192',
       '113', '2004', '822', '562', '23', '164', '733', '312'],
      dtype=object)

Reemplazamos los numeros en 'letras' a numeros en digitos

In [156]:
df['ambientes'].replace(numeros_en_letras , inplace=True)
df['ambientes'].unique()

array(['2', '1', nan, '4', '3', '5', '6', '042', '42026', '902', '18',
       '000', '944', '7', '8', '12', '43', '22', '42022', '281', '24',
       '20173', '1200', '772', '653', '983', '42025', '42004', '42046',
       '502', '42049', '152', '412', '42015', '42021', '172', '693',
       '622', '183', '793', '262', '253', '913', '20171', '20172', '853',
       '202', '192', '113', '2004', '822', '562', '23', '164', '733',
       '312'], dtype=object)

In [157]:
df.head(100)

,Unnamed: 0,barrio,lat,lon,total,cubierta,precio,piso,habs,expensas,descripcion,ambientes
0,2,Mataderos,-34.652262,-58.522982,55.0,55.0,1309.090909,NaN,NaN,NaN,2 AMBIENTES 3ER PISO LATERAL LIVING COMEDOR AM...,2
1,7,Belgrano,-34.559873,-58.443362,45.0,40.0,3066.666667,NaN,NaN,NaN,EXCELENTE MONOAMBIENTE A ESTRENAR AMPLIO SUPER...,1
2,8,Belgrano,-34.559873,-58.443362,65.0,60.0,3000.000000,NaN,NaN,NaN,EXCELENTE DOS AMBIENTES ESTRENAR AMPLIO SUPER...,2
3,19,Palermo,-34.580504,-58.405874,104.0,96.0,3365.384615,NaN,3.0,NaN,Excelente semipiso al contra frente en Bulnes ...,NaN
4,21,Palermo,-34.590926,-58.411665,118.0,73.0,2292.372881,NaN,4.0,NaN,"EXCELENTE ZONA, MULTIPLES MEDIOS DE TRANSPORTE...",NaN
5,29,Flores,-34.635118,-58.473964,43.0,43.0,1744.186047,NaN,2.0,NaN,Departamento muy luminoso con todos sus ambien...,NaN
6,35,Boedo,-34.621769,-58.422108,80.0,77.0,1812.500000,NaN,4.0,NaN,"Hermoso departamento de cuatro ambientes, refa...",4
7,48,Balvanera,-34.609675,-58.398659,141.0,124.0,1702.127660,NaN,5.0,NaN,"PISO 13, Orientación norte, disposición al fre...",NaN
8,52,Caballito,-34.622211,-58.439128,50.0,50.0,2200.000000,NaN,3.0,NaN,Departamento de 3 Ambientes al Contrafrente. S...,3
9,53,Caballito,-34.623894,-58.446861,100.0,46.0,1705.000000,NaN,2.0,NaN,14 exclusivos semi-pisos.Excelentes detalles d...,NaN
10,54,Caballito,-34.620928,-58.445874,81.0,75.0,2721.111111,NaN,3.0,NaN,"Excelentes detalles de terminación, y diseño.G...",NaN
11,55,Caballito,-34.620928,-58.445874,81.0,75.0,2750.370370,NaN,3.0,NaN,"Excelentes detalles de terminación, y diseño.G...",NaN
12,59,Caballito,-34.628786,-58.427783,70.0,67.0,1542.857143,NaN,3.0,NaN,"Al frente muy luminoso.Living comedor, a balco...",NaN
13,60,Nuñez,-34.553578,-58.455511,50.0,50.0,3460.000000,NaN,2.0,NaN,ESPECTACULAR DEPARTAMENTO DE 2 AMBIENTES CON C...,2
14,66,Boedo,-34.618777,-58.402645,38.0,NaN,1918.421053,NaN,NaN,1200.0,CODIGO: 5 ubicado en: Avenida Independencia 26...,1
15,120,Belgrano,-34.562697,-58.460157,55.0,55.0,3236.363636,12.0,NaN,NaN,"Depto de 3 amb. c/cochera cubierta, en piso 12...",3
16,157,Balvanera,-34.617226,-58.395943,80.0,80.0,1612.500000,NaN,4.0,NaN,Corredor Responsable: Daniel Acosta - CUCICBA ...,4
17,166,Caballito,-34.620725,-58.438704,51.0,51.0,2509.803922,6.0,2.0,NaN,Corredor Responsable: Mariano Aufseher - CUCIC...,2
18,167,Balvanera,-34.603172,-58.399464,71.0,71.0,1661.971831,NaN,NaN,NaN,Corredor Responsable: Mariano Aufseher - CUCIC...,2
19,178,Barrio Norte,-34.594304,-58.403685,35.0,35.0,2657.142857,NaN,1.0,NaN,Corredor Responsable: Alejandro Botta - CUCICB...,1
20,207,Villa Crespo,-34.597679,-58.443019,42.0,39.0,1757.142857,NaN,1.0,NaN,Emprendimiento Premium en Villa CrespoIDEAL IN...,NaN
21,208,Villa Crespo,-34.597290,-58.447654,44.0,41.0,1636.363636,NaN,1.0,NaN,Emprendimiento Premium en Villa CrespoIDEAL IN...,NaN
22,209,Las Cañitas,-34.564577,-58.437287,68.0,48.0,3455.882353,NaN,2.0,NaN,"Excelente 2 Ambientes orientacion Este, Muy lu...",2
23,210,Belgrano,-34.562084,-58.456686,57.0,54.0,4210.526316,NaN,2.0,NaN,DUPLEX CON COCHERA FIJA CUBIERTA 3 AÑOS DE ANT...,NaN
24,216,Belgrano,-34.562146,-58.449657,160.0,150.0,3437.500000,NaN,4.0,NaN,"Piso de categoría en Barrancas del Belgrano, e...",NaN
25,218,Villa Crespo,-34.597679,-58.443019,33.0,31.0,1878.787879,NaN,1.0,NaN,Emprendimiento Premium en Villa CrespoIDEAL IN...,NaN
26,220,Belgrano,-34.565265,-58.438233,69.0,53.0,3447.753623,NaN,2.0,NaN,El edificio está situado en el barrio de las ...,1
27,222,Flores,-34.625547,-58.468877,65.0,62.0,1523.076923,NaN,3.0,NaN,Departamento de 3 ambientesExcelente EstadoGas...,3
28,225,Nuñez,-34.542750,-58.460145,66.0,59.0,3469.696970,NaN,2.0,NaN,"Emplazado en el corzaón de Nuñez, Pedraza Plaz...",1
29,226,Nuñez,-34.542750,-58.460145,45.0,39.0,3000.000000,NaN,1.0,NaN,"Emplazado en el corzaón de Nuñez, Pedraza Plaz...",1
...,...,...,...,...,...,...,...,...,...,...,...,...
70,386,Palermo,-34.590243,-58.436402,70.0,61.0,2557.142857,NaN,3.0,NaN,EMPRENDIMIENTO A ESTRENAR *** Av. Córdoba 5202...,3
71,388,Almagro,-34.609694,-58.419819,77.0,72.0,2727.272727,NaN,4.0,NaN,MUY BUEN DEPARTAMENTO DE 4 AMBIENTES CON DEPEN...,4
72,401,Puerto Madero,-34.617915,-58.361766,54.0,50.0,6111.111111,NaN,2.0,NaN,COCHERA NO NCUIDA EN EL PRECIO u$s40.000En su ...,NaN
73,403,San Telmo,-34.626675,-58.372666,41.0,36.0,2642.829268,NaN,1.0,NaN,Gran OPORTUNIDAD de inversión a PRECIO CERRADO...,4
74,405,Almagro,-34.617691,-58.422826,56.0,47.0,2142.857143,NaN,3.0,NaN,MUY BUEN DEPARTAMENTO DE 3 AMBIENTES CON BALCÓ...,3
75,411,Monserrat,-34.613087,-58.381360,60.0,60.0,2000.000000,NaN,2.0,NaN,"consta de living de 8x4 con cocina integrada, ...",NaN
76,420,Belgrano,-34.574788,-58.463769,150.0,130.0,3466.666667,NaN,3.0,NaN,"En excelente zona, a metros de Av. Los Incas, ...",NaN
77,422,Recoleta,-34.591035,-58.400623,140.0,136.0,2700.000000,NaN,4.0,NaN,Edificio de categoria en excelentes condicione...,4
78,434,Flores,-34.618263,-58.467458,32.0,32.0,2250.000000,NaN,NaN,NaN,CODIGO: 2889-abc034 ubicado en: Alfredo Bufano...,1
79,435,Flores,-34.618263,-58.467458,120.0,50.0,1000.000000,NaN,NaN,NaN,CODIGO: 2889-abc 0351 ubicado en: Alfredo Bufa...,2
80,444,Palermo,-34.584890,-58.419000,43.0,43.0,2209.302326,NaN,2.0,NaN,Corredor Responsable: Raul Hector Merlo - CUCI...,2
81,450,Belgrano,-34.562043,-58.461685,44.0,44.0,2659.090909,NaN,2.0,NaN,Corredor Responsable: Luis Varela - CSI 5527 /...,2
82,476,Villa Urquiza,-34.572645,-58.482177,97.0,97.0,2371.134021,2.0,3.0,NaN,Corredor Responsable: Mariano Aufseher - CUCIC...,NaN
83,488,Villa Devoto,-34.587550,-58.510616,54.0,54.0,2629.629630,2.0,2.0,NaN,Corredor Responsable: Ariel Champanier - CUCIC...,2
84,491,Barrio Norte,-34.596335,-58.409886,122.0,122.0,2049.180328,1.0,NaN,NaN,Corredor Responsable: Uno Bienes Raices SRL - ...,NaN
85,496,Boca,-34.633761,-58.360234,83.0,74.0,1686.746988,NaN,3.0,NaN,"Pinzón 400. Departamento de 83 metros totales,...",NaN
86,558,Caballito,-34.620928,-58.445874,28.0,25.0,2339.285714,NaN,1.0,NaN,A estrenar estudio profesional / monoambiente ...,1
87,564,Boca,-34.634496,-58.363134,33.0,31.0,1606.060606,NaN,1.0,NaN,"Sobre la calle Pi y Margall, A Pocos Metros de...",1
88,565,Coghlan,-34.561508,-58.468823,104.0,80.0,2057.692308,NaN,4.0,NaN,*** EMPRENDIMIENTO FREIRE 2660 ***FREIRE 2660 ...,NaN
89,567,Palermo,-34.571150,-58.423297,106.0,100.0,2924.528302,NaN,3.0,NaN,"EXCELENTE, SEMIPISO, AL CONTRAFRENTE, A METROS...",NaN
90,636,Recoleta,-34.595598,-58.412713,43.0,43.0,3883.720930,NaN,2.0,NaN,Excelente departament 2 amb a estrenar en reco...,2
91,637,San Telmo,-34.621184,-58.373116,55.0,55.0,1709.090909,NaN,3.0,NaN,"Brandsen 467, CABA / departamento 3 ambientes ...",3
92,639,Boca,-34.634496,-58.363134,55.0,55.0,1709.090909,NaN,3.0,NaN,"Brandsen 467, CABA / departamento 3 ambientes ...",3
93,640,Barracas,-34.634537,-58.359175,55.0,55.0,1709.090909,NaN,3.0,NaN,"Brandsen 467, CABA / departamento 3 ambientes ...",3
94,641,Recoleta,-34.589546,-58.397364,28.0,28.0,3750.000000,NaN,1.0,NaN,Excelente departamento a estrenar en recoleta ...,NaN
95,643,Recoleta,-34.595598,-58.412713,37.0,37.0,3513.513514,NaN,1.0,NaN,Excelente departamento Monoambiente a estrenar...,1
96,645,Recoleta,-34.595598,-58.412713,61.0,61.0,3852.459016,NaN,2.0,NaN,Excelente departamento de 2 amb con posibilida...,2
97,647,Palermo,-34.592742,-58.406147,43.0,37.0,3604.651163,NaN,1.0,NaN,Excelente monoambiente a estrenar en una de la...,1
98,648,Palermo,-34.592742,-58.406147,75.0,51.0,3266.666667,NaN,1.0,NaN,Excelente monoambiente a estrenar en una de la...,1
99,656,Almagro,-34.597812,-58.425597,38.0,32.0,2065.526316,NaN,1.0,NaN,ESTADO DE ISRAEL 4272 - CERCA DE TODOEdificio ...,1

In [158]:
df['habitaciones_final'] = df['habs']
df['habitaciones_final'] = df['habitaciones_final'].fillna(df['ambientes'])
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15948 entries, 0 to 15947
Data columns (total 13 columns):
Unnamed: 0            15948 non-null int64
barrio                15948 non-null object
lat                   15948 non-null float64
lon                   15948 non-null float64
total                 15948 non-null float64
cubierta              15491 non-null float64
precio                15948 non-null float64
piso                  2465 non-null float64
habs                  10109 non-null float64
expensas              3956 non-null float64
descripcion           15948 non-null object
ambientes             11649 non-null object
habitaciones_final    14495 non-null object
dtypes: float64(8), int64(1), object(4)
memory usage: 1.6+ MB

In [159]:
df['habitaciones_final'] = df['habitaciones_final'].dropna().astype('int64')

Regex para info de los deptos

In [164]:
amenidades = 'r(balcon)|(cochera)|(patio)|(gimnasio|gym)|(terraza)|(sum)|(baulera)|(parrilla)'
df_amen = df['descripcion'].str.extract(amenidades , flags=re.IGNORECASE , expand=True)
df_amen.columns = ['balcon' , 'cochera' , 'patio' , 'gym' , 'terraza' , 'sum' , 'baulera' , 'parrilla']

df_amen.fillna(0 , inplace=True)
df_amen.head()

df_amen = df_amen.applymap(lambda x: 1 if len(str(x)) > 1 else 0)
df_amen.head()

   balcon  cochera  patio  gym  terraza  sum  baulera  parrilla
0       0        0      0    0        0    0        0         0
1       0        0      0    0        0    0        0         0
2       0        0      0    0        0    0        0         0
3       0        0      0    0        1    0        0         0
4       0        0      1    0        0    0        0         0

In [165]:
df_amen.head(100)

    balcon  cochera  patio  gym  terraza  sum  baulera  parrilla
0        0        0      0    0        0    0        0         0
1        0        0      0    0        0    0        0         0
2        0        0      0    0        0    0        0         0
3        0        0      0    0        1    0        0         0
4        0        0      1    0        0    0        0         0
5        0        0      0    0        0    0        0         0
6        0        0      0    0        0    0        0         0
7        0        0      0    0        1    0        0         0
8        0        0      0    0        0    0        1         0
9        0        0      0    0        0    0        0         0
10       0        1      0    0        0    0        0         0
11       0        1      0    0        0    0        0         0
12       0        0      0    0        0    0        0         0
13       0        1      0    0        0    0        0         0
14       0        0      0    0        0    0        0         0
15       0        1      0    0        0    0        0         0
16       0        0      0    0        0    1        0         0
17       0        0      0    0        0    0        1         0
18       0        0      0    0        0    0        0         0
19       0        0      0    0        0    0        0         0
20       0        1      0    0        0    0        0         0
21       0        1      0    0        0    0        0         0
22       0        0      0    0        0    1        0         0
23       0        1      0    0        0    0        0         0
24       0        1      0    0        0    0        0         0
25       0        1      0    0        0    0        0         0
26       0        1      0    0        0    0        0         0
27       0        0      0    0        0    0        0         0
28       0        0      0    0        1    0        0         0
29       0        0      0    0        1    0        0         0
..     ...      ...    ...  ...      ...  ...      ...       ...
70       0        0      0    0        1    0        0         0
71       0        1      0    0        0    0        0         0
72       0        1      0    0        0    0        0         0
73       0        0      0    0        1    0        0         0
74       0        0      0    0        0    0        0         0
75       0        0      0    0        0    0        0         0
76       0        1      0    0        0    0        0         0
77       0        0      0    0        0    0        1         0
78       0        0      0    0        0    0        0         0
79       0        0      0    0        1    0        0         0
80       0        0      0    0        0    0        0         0
81       0        0      1    0        0    0        0         0
82       0        1      0    0        0    0        0         0
83       0        0      0    0        1    0        0         0
84       0        0      1    0        0    0        0         0
85       0        0      0    0        0    0        0         0
86       0        0      0    0        1    0        0         0
87       0        0      0    0        0    0        0         0
88       0        0      0    0        1    0        0         0
89       0        1      0    0        0    0        0         0
90       0        0      0    0        0    1        0         0
91       0        0      0    0        0    0        1         0
92       0        0      0    0        0    0        1         0
93       0        0      0    0        0    0        1         0
94       0        0      0    0        0    1        0         0
95       0        0      0    0        0    1        0         0
96       0        0      0    0        0    1        0         0
97       0        0      0    0        1    0        0         0
98       0        0      0    0        1    0        0         0
99       0        0      0    0        0    1        0         0

[100 rows x 8 columns]

In [169]:
df = df.join(df_amen)

In [170]:
df

,Unnamed: 0,barrio,lat,lon,total,cubierta,precio,piso,habs,expensas,...,ambientes,habitaciones_final,balcon,cochera,patio,gym,terraza,sum,baulera,parrilla
0,2,Mataderos,-34.652262,-58.522982,55.0,55.0,1309.090909,NaN,NaN,NaN,...,2,2.0,0,0,0,0,0,0,0,0
1,7,Belgrano,-34.559873,-58.443362,45.0,40.0,3066.666667,NaN,NaN,NaN,...,1,1.0,0,0,0,0,0,0,0,0
2,8,Belgrano,-34.559873,-58.443362,65.0,60.0,3000.000000,NaN,NaN,NaN,...,2,2.0,0,0,0,0,0,0,0,0
3,19,Palermo,-34.580504,-58.405874,104.0,96.0,3365.384615,NaN,3.0,NaN,...,NaN,3.0,0,0,0,0,1,0,0,0
4,21,Palermo,-34.590926,-58.411665,118.0,73.0,2292.372881,NaN,4.0,NaN,...,NaN,4.0,0,0,1,0,0,0,0,0
5,29,Flores,-34.635118,-58.473964,43.0,43.0,1744.186047,NaN,2.0,NaN,...,NaN,2.0,0,0,0,0,0,0,0,0
6,35,Boedo,-34.621769,-58.422108,80.0,77.0,1812.500000,NaN,4.0,NaN,...,4,4.0,0,0,0,0,0,0,0,0
7,48,Balvanera,-34.609675,-58.398659,141.0,124.0,1702.127660,NaN,5.0,NaN,...,NaN,5.0,0,0,0,0,1,0,0,0
8,52,Caballito,-34.622211,-58.439128,50.0,50.0,2200.000000,NaN,3.0,NaN,...,3,3.0,0,0,0,0,0,0,1,0
9,53,Caballito,-34.623894,-58.446861,100.0,46.0,1705.000000,NaN,2.0,NaN,...,NaN,2.0,0,0,0,0,0,0,0,0
10,54,Caballito,-34.620928,-58.445874,81.0,75.0,2721.111111,NaN,3.0,NaN,...,NaN,3.0,0,1,0,0,0,0,0,0
11,55,Caballito,-34.620928,-58.445874,81.0,75.0,2750.370370,NaN,3.0,NaN,...,NaN,3.0,0,1,0,0,0,0,0,0
12,59,Caballito,-34.628786,-58.427783,70.0,67.0,1542.857143,NaN,3.0,NaN,...,NaN,3.0,0,0,0,0,0,0,0,0
13,60,Nuñez,-34.553578,-58.455511,50.0,50.0,3460.000000,NaN,2.0,NaN,...,2,2.0,0,1,0,0,0,0,0,0
14,66,Boedo,-34.618777,-58.402645,38.0,NaN,1918.421053,NaN,NaN,1200.0,...,1,1.0,0,0,0,0,0,0,0,0
15,120,Belgrano,-34.562697,-58.460157,55.0,55.0,3236.363636,12.0,NaN,NaN,...,3,3.0,0,1,0,0,0,0,0,0
16,157,Balvanera,-34.617226,-58.395943,80.0,80.0,1612.500000,NaN,4.0,NaN,...,4,4.0,0,0,0,0,0,1,0,0
17,166,Caballito,-34.620725,-58.438704,51.0,51.0,2509.803922,6.0,2.0,NaN,...,2,2.0,0,0,0,0,0,0,1,0
18,167,Balvanera,-34.603172,-58.399464,71.0,71.0,1661.971831,NaN,NaN,NaN,...,2,2.0,0,0,0,0,0,0,0,0
19,178,Barrio Norte,-34.594304,-58.403685,35.0,35.0,2657.142857,NaN,1.0,NaN,...,1,1.0,0,0,0,0,0,0,0,0
20,207,Villa Crespo,-34.597679,-58.443019,42.0,39.0,1757.142857,NaN,1.0,NaN,...,NaN,1.0,0,1,0,0,0,0,0,0
21,208,Villa Crespo,-34.597290,-58.447654,44.0,41.0,1636.363636,NaN,1.0,NaN,...,NaN,1.0,0,1,0,0,0,0,0,0
22,209,Las Cañitas,-34.564577,-58.437287,68.0,48.0,3455.882353,NaN,2.0,NaN,...,2,2.0,0,0,0,0,0,1,0,0
23,210,Belgrano,-34.562084,-58.456686,57.0,54.0,4210.526316,NaN,2.0,NaN,...,NaN,2.0,0,1,0,0,0,0,0,0
24,216,Belgrano,-34.562146,-58.449657,160.0,150.0,3437.500000,NaN,4.0,NaN,...,NaN,4.0,0,1,0,0,0,0,0,0
25,218,Villa Crespo,-34.597679,-58.443019,33.0,31.0,1878.787879,NaN,1.0,NaN,...,NaN,1.0,0,1,0,0,0,0,0,0
26,220,Belgrano,-34.565265,-58.438233,69.0,53.0,3447.753623,NaN,2.0,NaN,...,1,2.0,0,1,0,0,0,0,0,0
27,222,Flores,-34.625547,-58.468877,65.0,62.0,1523.076923,NaN,3.0,NaN,...,3,3.0,0,0,0,0,0,0,0,0
28,225,Nuñez,-34.542750,-58.460145,66.0,59.0,3469.696970,NaN,2.0,NaN,...,1,2.0,0,0,0,0,1,0,0,0
29,226,Nuñez,-34.542750,-58.460145,45.0,39.0,3000.000000,NaN,1.0,NaN,...,1,1.0,0,0,0,0,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15918,120197,Nuñez,-34.549481,-58.469229,48.0,39.0,2643.750000,NaN,1.0,NaN,...,1,1.0,0,0,0,0,0,1,0,0
15919,120198,Nuñez,-34.549481,-58.469229,115.0,96.0,2688.695652,NaN,3.0,NaN,...,3,3.0,0,0,0,0,0,1,0,0
15920,120199,Nuñez,-34.549481,-58.469229,56.0,40.0,2525.000000,NaN,1.0,NaN,...,1,1.0,0,0,0,0,0,1,0,0
15921,120217,Recoleta,-34.590285,-58.400306,71.0,71.0,2394.366197,NaN,NaN,NaN,...,3,3.0,0,0,0,0,0,0,0,0
15922,120229,Capital Federal,-34.598507,-58.389604,32.0,32.0,3281.250000,NaN,NaN,NaN,...,2,2.0,0,0,0,0,0,0,0,0
15923,120303,Barrio Norte,-34.591621,-58.398238,143.0,135.0,2937.062937,NaN,NaN,10000.0,...,NaN,NaN,0,1,0,0,0,0,0,0
15924,120935,Recoleta,-34.593480,-58.405057,84.0,73.0,3154.761905,NaN,NaN,1400.0,...,NaN,NaN,0,0,1,0,0,0,0,0
15925,120963,Flores,-34.615065,-58.474742,42.0,38.0,2119.047619,NaN,NaN,2000.0,...,2,2.0,0,0,0,0,0,0,0,0
15926,120976,Palermo,-34.578006,-58.427334,45.0,45.0,1666.666667,NaN,NaN,1800.0,...,2,2.0,0,0,0,0,0,0,0,0
15927,120984,Caballito,-34.620403,-58.441022,77.0,77.0,1909.090909,NaN,NaN,3800.0,...,3,3.0,0,0,0,0,0,0,0,0
15928,121059,Monserrat,-34.613408,-58.384543,37.0,34.0,2310.810811,NaN,NaN,1200.0,...,1,1.0,0,1,0,0,0,0,0,0
15929,121064,Boca,-34.631853,-58.360973,35.0,NaN,1857.142857,NaN,NaN,1209.0,...,2,2.0,0,0,0,0,0,0,1,0
15930,121075,Caballito,-34.627467,-58.438661,91.0,83.0,3461.538462,NaN,NaN,3000.0,...,4,4.0,0,1,0,0,0,0,0,0
15931,121077,Belgrano,-34.567016,-58.462525,70.0,30.0,2428.571429,NaN,NaN,2500.0,...,2,2.0,0,0,0,0,1,0,0,0
15932,121093,Palermo,-34.570179,-58.432229,90.0,85.0,6888.888889,NaN,NaN,8000.0,...,NaN,NaN,0,1,0,0,0,0,0,0
15933,121094,Belgrano,-34.561900,-58.461039,84.0,81.0,2595.238095,NaN,NaN,5050.0,...,4,4.0,0,1,0,0,0,0,0,0
15934,121103,Coghlan,-34.561900,-58.461039,84.0,81.0,2595.238095,NaN,NaN,5050.0,...,4,4.0,0,1,0,0,0,0,0,0
15935,121107,Belgrano,-34.568150,-58.455620,35.0,35.0,3142.857143,NaN,NaN,NaN,...,2,2.0,0,0,0,0,0,0,0,0
15936,121113,Palermo,-34.595668,-58.415143,100.0,88.0,2650.000000,NaN,NaN,NaN,...,3,3.0,0,0,0,0,1,0,0,0
15937,121120,Palermo,-34.593015,-58.428296,45.0,40.0,3555.555556,NaN,NaN,NaN,...,1,1.0,0,0,0,0,0,1,0,0
15938,121121,Barrio Norte,-34.597132,-58.398943,29.0,24.0,2034.482759,NaN,NaN,900.0,...,1,1.0,0,0,1,0,0,0,0,0
15939,121128,Belgrano,-34.556865,-58.447706,94.0,94.0,3819.148936,NaN,NaN,NaN,...,NaN,NaN,0,1,0,0,0,0,0,0
15940,121131,Recoleta,-34.590628,-58.397539,113.0,113.0,2876.106195,NaN,NaN,5100.0,...,4,4.0,0,0,0,0,0,0,0,0
15941,121150,Paternal,-34.608703,-58.476204,52.0,52.0,1826.923077,NaN,NaN,1200.0,...,NaN,NaN,0,0,0,0,0,0,0,0
15942,121151,Flores,-34.629505,-58.460642,72.0,72.0,1666.666667,NaN,NaN,6500.0,...,NaN,NaN,0,0,0,0,0,0,0,0
15943,121152,Caballito,-34.623443,-58.455030,33.0,33.0,2257.575758,NaN,NaN,NaN,...,1,1.0,0,0,0,0,0,0,0,0
15944,121153,Barrio Norte,-34.599214,-58.402519,91.0,65.0,1813.186813,NaN,NaN,NaN,...,NaN,NaN,0,0,0,0,1,0,0,0
15945,121158,Recoleta,-34.587425,-58.397372,44.0,39.0,3750.000000,NaN,NaN,NaN,...,1,1.0,0,0,0,0,0,0,0,1
15946,121160,Belgrano,-34.563685,-58.442683,157.0,NaN,2611.464968,NaN,NaN,6300.0,...,NaN,NaN,0,0,0,0,0,0,1,0
15947,121217,Villa Urquiza,-34.570639,-58.475596,46.0,39.0,2858.695652,NaN,NaN,NaN,...,1,1.0,0,0,0,0,0,0,0,1

In [171]:
df.to_csv("properatti_explore_desc.csv")